### ISSUE TITLE
The touch, is it worth it?

### ISSUE THREAD

**Issue by Paul-Ver** [davidmpye/Sonoff-Touch-MQTT#4]
### Background

Your Github is actually the first resource I can find on modifying the Sonos Touch, thank you for sharing!
I'm also thinking of writing my own software for it, but probably not using MQTT, I'd rather use a more low level option like IP multicast (it's funny it uses mDNS but not multicast for messaging?).
(The default firmware is worthless, I've heard)
I've got two in-line types of Sonoffs on my way and I'm thinking of buying a touch version, since it'd be nice to fit it inside the wall to control the lamp on my ceiling.

### Question(s)

- Could you do the hardware teardown page? Before I buy one, I want to see how easy it is to open up and/or if it's likely to break. (Is it just plastic pinched together?)
- ~~Wiring diagrams show L and N going in, but only L going out. Is the Neutral just connected to both the lamp and the neutral and the sonoff just switches the live?~~ (It seems obvious after watching some images on wiring regular switches)
- You mention the header being 3V3, I couldn't find which model of ESP8266 it is, but are the RX/TX lines 5V compatible?
- In [this video](https://youtu.be/8mz5sCAvDAY?t=2m27s) the person tells that OTA uses a lot of memory (he claims half), have you had any issues with memory and/or howmany space (percentage) does your sketch use? Does it matter how many times you upload a new version?

If you could answer some of my questions, I may put in some effort to update the Wiki with it.
And I may buy a sonoff touch aswell and do some further investigation (I'm thinking of porting/abstracting the library to also work on the normal sonoff switch (if that doesn't work already)).

I'll also have to check if the sonoff touch can handle the spots I have, before I wire it up and burn the house down 👍

**Comment by davidmpye** [comment]
Hi,

might get a chance to do the teardown soon.  

To answer your questions

1) Yep, as above.  It's a plastic clip together rear shell, which screw-mounts to the wall-box.  The screws also press/hold the 2 halves together.  The glass touch bit (it is glass) is then pushed in and is a firm fit on top.   I think it looks quite nice and certainly seems robust.  It requires prying to remove the glass faceplate.

2)  It needs L+N to provide power for itself.   The L-out is switched by relay.

3) The IO pins should be 5v tolerant BUT the VCC is definitely 3v3.  It would be safer to run everything as 3v3.   It isn't an ESP8266, it's an ESP8255 (difference being that a 1M flash chip is on die).  

4) OTA update requires that your firmware is smaller than 50% of the available flash space.  This is because the new firmware is uploaded into the other 'spare' half of flash, then a flag is set to tell the bootloader code which code area contains the 'live' firmware.  You should have tens of thousands of code uploads possible before the flash starts to fatigue.  The ESP8255 has integral non-upgradeable flash storage.  My firmware.bin file here (just test compiled it) is 250k.

It's capable of switching 2A using it's onboard relay.

The code works just fine on 'non-touch' switches too, though a minor logic change (ie debounce) is probably needed if you want the onboard button to work.

Although I bought one of these, I don't actually use it at the moment because I haven't found an easy way to get a neutral wire down to my switches, so I actually use the inline ones connected to the ceiling rose ( not sure if you're in the UK, I know a lot of countries run things differently).

David

**Comment by splodgemcroo** [comment]
Any idea whether this would work without anything connected to the switched live out?  I also have no neutrals in my switches - but I've already got smart bulbs, so I was wondering whether I could just re-wire the ceiling rose so that the light fitting is always on, and reconnect the two wires going to the switch to live/neutral (rather than live/switched-live). Then I could just use the sonoff touch as a remote switch, sending messages to my home automation controller via mqtt/whatever, and switch the smart bulb on/off that way.

Whether this would all be 'allowed' under UK wiring regulations is another question of course..

**Comment by joshuagti** [comment]
@splodgemcroo I have thought the same, I live in a rented house so will have to be careful about any wiring changes. Better than rewiring the earth for the light switch to be a neutral...

**Comment by davidmpye** [comment]
Yep, it will work fine that way, if you don't want to use the switched
'out'.

Just connect permanent L and N, and use the MQTT messages to turn the bulbs
on/off.

Only drawback is if your MQTT server/LAN etc fails, then you'l be left in
the dark...

David

**Comment by davidmpye** [comment]
I don't agree about that.  Using the earth conn (usually bare wire in UK
twin+earth wiring) is pretty scary in my mind.

If you rewire things at the ceiling rose so L and N are put down to the
switch rather than L and switched L return, that seems safer.

Downside to that is that if someone comes along and puts a standard switch
on in future, flipping it will short L + N.

David

**Comment by davidmpye** [comment]
Sorry, slightly misread what you said Josh - I think we're both roughly
coming from the same angle!

There is a 3rd way of doing things: I have been using the 'normal' Sonoffs
like this:

Wire them into the ceiling (remove ceiling rose, and push it up into the
cavity behind, with a L and N feed from the rose to the sonoff, and the
switched live output wired to turn the light on.  I have added a PCB header
to the PCB of the sonoff using the spare GPIO and gnd and wire them to the
original feed to the light switch, so the light switch now just toggles the
sonoff GPIO (which then toggles the light state).

Means I haven't had to run new wiring down to the switches (but doesn't
look quite as cool as the Sonoff Touches...!)

David


David

**Comment by splodgemcroo** [comment]
ooh - i like that idea of using the normal sonoff in the ceiling cavity that way, i think that would definitely work for me - and I like the idea of the system being independent of the mqtt server under normal operation as well.  I think I'm going to get some testing set up on the bench and give it a try - thanks!

**Comment by davidmpye** [comment]
No problem.

The s/w is elsewhere on my github (
https://github.com/davidmpye/Sonoff-Ceiling-Lighting )

That uses a standard sonoff, two wires (spare GPIO and GND) which I connect
to the original 2 core cable going to my domestic light switch.  That way,
the light switch just toggles the GPIO.

David

**Comment by xbmcnut** [comment]
Hi David. Like your work. Where is the 'spare' GPIO on the standard Sonoff?

**Comment by davidmpye** [comment]
The programming header has 5 pins - of which we usually use 4 (3v3, gnd,
rx, tx).  The fifth pin is GPIO 14.

If you orient the sonoff PCB with the push-switch at the TOP, the pin at
the bottom (closest to the long row of pins used for the RF module (if
fitted!)) is the spare GPIO  (gpio pin 14).

I picked up GND from the long header for the unused RF module.  (it's at
the extreme right if looking at the board with push-swtich at the top).

I'll try to find some pics to add to the  https://github.com/
davidmpye/Sonoff-Ceiling-Lighting repo when I get a chance.

David

**Comment by xbmcnut** [comment]
@davidmpye Thanks for the prompt reply. Mine all have 5 pin headers so good to go. Appreciate the heads up.

**Comment by jjssoftware** [comment]
Hi David,

As a UK resident looking for a automated lighting solution, I'd just like to say that I really appreciate your work here too. It's a shame there's a bit of a gap in the itead docs for their kit and potential use in the UK and it took me a while to realize that the touch switch won't work here where switches that have no neutral wire present. Your idea of using a regular sonoff power switch (https://www.itead.cc/smart-home/sonoff-wifi-wireless-switch.html) pushed into the cavity above the light is fabulous and I'll be going down that path myself.

Thanks again
Joe

**Comment by davidmpye** [comment]
Cheers Joe, glad it's been of use.

**Comment by fguiet** [comment]
Hi guys,
Just to share info for orhers, I am french résident and same thing here : no neutral in switches so those Natty things are not working over here.
Voilà
Fred

**Comment by vvallee** [comment]
Hey all, I know this is an older thread, but was hoping someone can confirm the proper wiring for the Touch? I have Lin and Lout wired to the 2 hot wires (black) and Nin wired to neutral which connects to the two passthrough neutral wires via twist connector.
No power to the unit in this configuration, however it flashed just fine.

**Comment by davidmpye** [comment]
Surely the two hot wires you are referring to are:

Live in (from fuseboard/lighting ring main)

Live out (switched by the sonoff touch, to the light bulbs)

Are they the right way round?

**Comment by vvallee** [comment]
Yes correct as you mentioned, I believe they are the right way around, but will triple check that.

**Comment by vvallee** [comment]
My wiring was correct. The issue was that I had to hit the touchpad for the lights to come on initially. I thought it had no power because they lights didn't come on as they did when flashing the ESP.
